version: '3.7'

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp

    volumes:
      - ./flask/:/app


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - "80:80"

  mymongo:
    build: ./mongodb
    container_name: mongo
    ports:
      - "27017:27017"

